### ISSUE TITLE
Import third_party error

### ISSUE THREAD

**Issue by clement-moulin-frier** [flowersteam/explauto#55]
Hi,

Right after a fresh install of explauto, running:

```
python -c "import explauto"
```

raises the following error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "explauto/__init__.py", line 7, in <module>
    from .sensorimotor_model.sensorimotor_model import SensorimotorModel
  File "explauto/sensorimotor_model/__init__.py", line 7, in <module>
    module = importlib.import_module('explauto.sensorimotor_model.{}'.format(mod_name))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "explauto/sensorimotor_model/non_parametric.py", line 5, in <module>
    from ..third_party.models.models.learner import Learner
ImportError: No module named third_party.models.models.learner
```

From what I remember, we removed the `third_party` package more than a year ago. However, it seems that it is still used in `non_parametric.py`(in particular the `Learner` class).

@pierre-rouanet: do you remember the status of this?
@sebastien-forestier: do you still use the `non_parametric` module? (e.g. for your LWR+CMAES inverse model?). Or do you rely on another module for LWR?

@jypuigbo: as a temporary fix you can:
- install the library in developer mode, as [explained here](http://flowersteam.github.io/explauto/installation.html#as-a-developer). Then comment the problematic line
```
 File "explauto/sensorimotor_model/non_parametric.py", line 5, in <module>
    from ..third_party.models.models.learner import Learner
```
and reinstall again. The error should disappear (you won't be able to use the `non_parametric` module though. You can also check with @santmarti who recently installed it without mentioning this problem.

Cheers

**Comment by sebastien-forestier** [comment]
I worked on that issue in branch models.
There I included directly and simplified only the useful code from Learner, so we can still use LWLR, WNN, BFGS, CMAES.
I suggest that we discuss merging the changes here: https://github.com/flowersteam/explauto/pull/56
By the time we merge them, you can use branch models to have sensorimotor models working, or do the trick suggested by @clement-moulin-frier.
Cheers

**Comment by jypuigbo** [comment]
@clement-moulin-frier The change worked for me. Thanks a lot!
