### ISSUE TITLE
forward/inverse check

### ISSUE THREAD

**Issue by x75** [flowersteam/explauto#73]
in sensorimotor models there is a check for wether we do a forward or inverse prediction like

`if in_dims == self.m_dims and out_dims == self.s_dims:  # forward`
`elif in_dims == self.s_dims and out_dims == self.m_dims:  # inverse`

if s_dims and m_dims happen to be equal i guess this will fail?

**Comment by sebastien-forestier** [comment]
Hi,

The objects self.m_dims, self.s_dims, in_dims and out_dims are all lists of integers.

For instance, using a 3 DOFs arm with the 3D position of the hand as sensory space, self.m_dims would be [0, 1, 2] and self.s_dims would be [3, 4, 5].

Thus if you ask an inference with in_dims=[0, 1, 2] and out_dims=[3, 4, 5] then it will do forward prediction, and with the reverse it will perform inverse inference.

Thanks for asking, maybe we should add some clarifying comments in this file.

Best,
