### ISSUE TITLE
sensorimotor model I/O mapping

### ISSUE THREAD

**Issue by x75** [flowersteam/explauto#74]
from a quick check it appears to me that explauto explicitly assumes a fixed starting state or, equivalently, kinematic motion?

explauto: m -> FWD -> s_{t+1}, s_{t+1} -> INV -> m

desired: (s_t, m) -> FWD -> s_{t+1}, (s_t, s_{t+1}) -> INV -> m) with (): vector concatenation

could this be done in a minimally invasive manner?

**Comment by sebastien-forestier** [comment]
Hi,

This feature has recently been added in Explauto.
I described it in [this](http://nbviewer.jupyter.org/github/flowersteam/explauto/blob/master/notebook/learning_with_sensorimotor_context.ipynb) notebook.

You are welcome to test it with your own environment, and to report any trouble or bug you might encounter!

Best,

**Comment by x75** [comment]
ah, tres cool. back at it .. :)

:+1:
