### ISSUE TITLE
ImportError: No module named 'inverse' (Python 3.4)

### ISSUE THREAD

**Issue by nDiv** [flowersteam/explauto#81]
Hi guys,

I found what might be a minor issue when I tried to use explauto in Python 3.4. After installing from source I ran: python3 -c "import explauto" and I got this import error: ImportError: No module named 'inverse'. I didn't have this issue when I ran the command with Python 2.7 though.

The file it was actually complaining about is: ../explauto/explauto/sensorimotor_model/inverse/jacobian.py", line 4, in <module>
    import inverse

I looked at another inverse model file (nn.py) and I saw that this line was used: "import .inverse", instead of "import inverse" (without a "dot" before inverse). I included the "dot" in jacobain.py and the import error disappeared.

Is this an actual issue or is there something wrong with they way I installed on my machine?

**Comment by sebastien-forestier** [comment]
Hi nDiv,
Indeed the library was mainly tested with Python 2.7 and there are some errors with Python 3.
I will check compatibility with Python 3 when I have time.
Thanks,
Sébastien

**Comment by sebastien-forestier** [comment]
Should be fixed by [this](https://github.com/flowersteam/explauto/commit/5d1c853b8b7b82e5c5a139bf165484a25b286d0c) commit.
