### ISSUE TITLE
Broken dependency in PIP installation

### ISSUE THREAD

**Issue by dantistus** [flowersteam/explauto#87]
I have tried to install explauto with `pip install explauto` and it has pulled the latest version of `scikit-learn` which has GMM deprecated and removed:

https://scikit-learn.org/0.18/modules/generated/sklearn.mixture.GMM.html

The issue seems to be fixed in developer version, but please consider making a new release. Thank you :)

**Comment by sebastien-forestier** [comment]
Hi @dantistus , 
It should be fine now with explauto 1.4.0
Sébastien

**Comment by dantistus** [comment]
Sorry for reopening. I have recently installed explauto on two systems (windows 10 and ubuntu 18) and on both `pip install explauto` installed version 1.3.0:

`pip show explauto`

```
Name: explauto
Version: 1.3.0
Summary: Python Library for Autonomous Exploration
Home-page: https://github.com/flowersteam/explauto
Author: Clement Moulin-Frier, Pierre Rouanet, Sebastien Forestier
Author-email: sebastien.forestier@inria.fr
License: GNU GENERAL PUBLIC LICENSE Version 3
Location: /home/user/explauto/build/lib
Requires: numpy, scikit-learn, scipy
```

**Comment by sebastien-forestier** [comment]
I just uploaded this morning explauto 1.4.0 on Pypi, so did you upgrade ?
`pip install --upgrade`

**Comment by dantistus** [comment]
Aha, sorry, I didn't :) Thank you again very much!
